### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlexShepherd** [AlexShepherd28/Poker#1]
- [x] Implement Card class
- [x] Implement Deck class
- [x] Implement Hand class
- [ ] Remove Deal class and reallocate in main method
- [ ] Implement Pot class
- [ ] Implement GUI class
- [ ] Implement Player class
- [ ] Implement Poker class
- [ ] Implement HandRanker class
- [ ] Create dB of poker hands

**Comment by AlexShepherd28** [comment]
- [x ] Implement Card class
- [x ] Implement Deck class
- [ ] Implement Player class
- [ ] Implement PlayerHand class
- [ ] Implement PokerHand class
- [ ] Implement Poker class
- [ ] Create dB of poker hands
